# docker-compose.yml
# Orquestación de servicios en contenedores (PostgreSQL)

services:
  db:
    image: postgres:17-alpine
    container_name: edificio_xyz_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations/001_initial_schema.sql:/docker-entrypoint-initdb.d/001_initial_schema.sql

volumes:
  postgres_data: